### ISSUE TITLE
Version 2022.5.18 incompatible with Python 3.5: AttributeError: module 'os' has no attribute 'PathLike'

### ISSUE THREAD

**Issue by Edward-Knight** [certifi/python-certifi#195]
The type hinting added in the latest version isn't compatible with Python 3.5, triggering: `AttributeError: module 'os' has no attribute 'PathLike'`.

Reproduction in an Ubuntu Xenial Docker container:
```
$ apt update
$ apt install -y python3-pip
$ pip3 install --upgrade "pip<21"  # latest version of pip compatible with 3.5
$ pip3 install certifi==2022.5.18
$ python3 --version
Python 3.5.2
$ python3 -c "import certifi"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/certifi/core.py", line 14, in <module>
    from importlib.resources import path as get_path, read_text
ImportError: No module named 'importlib.resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/usr/local/lib/python3.5/dist-packages/certifi/core.py", line 46, in <module>
    Resource = Union[str, "os.PathLike"]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
    self._eval_type(globalns, localns)
  File "/usr/lib/python3.5/typing.py", line 177, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
AttributeError: module 'os' has no attribute 'PathLike'
```

**Comment by zifban** [comment]
I have the same problem. [PR](https://github.com/certifi/python-certifi/pull/167) should solve it by updating `python_requires` to `>=3.6` and dropping support for Python 3.5.

**Comment by alex** [comment]
I've gone ahead and merged that PR.

**Comment by JoeJasinski** [comment]
I'd love to upgrade off of 3.5, but unfortunately can't yet. I know 3.5 not supported. Would it be possible to put in a code path for 3.5? It looks like it just has an issue with this type annotation. 

https://github.com/certifi/python-certifi/blob/2022.05.18/certifi/core.py#L46

**Comment by zifban** [comment]
The PR solved it for 2022.5.18.1, that won't get installed with Python 3.5. due to the `python_requires>=3.6`. Unfortunately the release 2022.5.18 still gets installed due to the `python_requires>=3.5` still in it and fails in use.

**Comment by bparzella** [comment]
Are there any plans to yank the 2022.5.18 from pypi? As python 3.5 pip still sees this release as latest supported version for 3.5, legacy installations still have problems with certifi.

**Comment by Lukasa** [comment]
Done.

**Comment by alex** [comment]
This should be fixed now.
